### ISSUE TITLE
Unable to change background color of gps text 

### ISSUE THREAD

**Issue by siduck** [SmiteshP/nvim-gps#108]
Hi there! Ive changed the symbol colors but the bg color of the text doesnt change ( even in my statusline )

The symbols take colors from my cmpkind highlight groups

![image](https://user-images.githubusercontent.com/59060246/171839891-935c05fc-570c-4129-abb5-8e64c8280f02.png)

But Im unable to change the background color of the text of gps (plugins, config in this case)

![image](https://user-images.githubusercontent.com/59060246/171839961-4d3ee398-ff59-4fba-8232-13a00d7aa0b8.png)

**Comment by CSpencerND** [comment]
Similar issue on lualine. Basically same config.
![image](https://user-images.githubusercontent.com/61397897/171872781-d7ea585a-66fe-4761-8178-26714795d0e5.png)

**Comment by siduck** [comment]
> Similar issue on lualine with the exact same config. ![image](https://user-images.githubusercontent.com/61397897/171872781-d7ea585a-66fe-4761-8178-26714795d0e5.png)

the symbols seem to use bg color from cmpkind highlight groups but the text look normal to me :think

**Comment by siduck** [comment]
Fixed the issue 

![image](https://user-images.githubusercontent.com/59060246/172037842-c3dcc337-e2e7-4b03-86c8-c4fbf259a257.png)

**Comment by siduck** [comment]
I defined a separate list of highlight groups for GPS ( which changes fg/bg color of the symbols) and change bg color of "Statusline" highlight group, ig gps uses that for its text

**Comment by LamprosPitsillos** [comment]
> I defined a separate list of highlight groups for GPS ( which changes fg/bg color of the symbols) and change bg color of "Statusline" highlight group, ig gps uses that for its text

Could you please explain a bit more on how you fixed this? I am having a hard time adding colors to gps-nvim. Thanks

**Comment by siduck** [comment]
> > I defined a separate list of highlight groups for GPS ( which changes fg/bg color of the symbols) and change bg color of "Statusline" highlight group, ig gps uses that for its text
> 
> Could you please explain a bit more on how you fixed this? I am having a hard time adding colors to gps-nvim. Thanks

```lua
local present, gps = pcall(require, "nvim-gps")

if not present then
   return
end

local icons = require "plugins.configs.lspkind_icons"

local options = {
   depth = 5,

   icons = {
      ["class-name"] = "%#GpsItemKindClass#" .. icons.Class .. "%*" .. " ",
      ["function-name"] = "%#GpsItemKindFunction#" .. icons.Function .. "%*" .. " ",
      ["method-name"] = "%#GpsItemKindMethod#" .. icons.Method .. "%*" .. " ",
      ["container-name"] = "%#GpsItemKindProperty#" .. icons.Object .. "%*" .. " ",
      ["tag-name"] = "%#GpsItemKindKeyword#" .. icons.Tag .. "%*" .. " ",
      ["mapping-name"] = "%#GpsItemKindProperty#" .. icons.Object .. "%*" .. " ",
      ["sequence-name"] = "%GpsItemKindProperty#" .. icons.Array .. "%*" .. " ",
      ["null-name"] = "%GpsItemKindField#" .. icons.Field .. "%*" .. " ",
      ["boolean-name"] = "%GpsItemKindValue#" .. icons.Boolean .. "%*" .. " ",
      ["integer-name"] = "%GpsItemKindValue#" .. icons.Number .. "%*" .. " ",
      ["float-name"] = "%GpsItemKindValue#" .. icons.Number .. "%*" .. " ",
      ["string-name"] = "%GpsItemKindValue#" .. icons.String .. "%*" .. " ",
      ["array-name"] = "%GpsItemKindProperty#" .. icons.Array .. "%*" .. " ",
      ["object-name"] = "%GpsItemKindProperty#" .. icons.Object .. "%*" .. " ",
      ["number-name"] = "%GpsItemKindValue#" .. icons.Number .. "%*" .. " ",
      ["table-name"] = "%GpsItemKindProperty#" .. icons.Table .. "%*" .. " ",
      ["date-name"] = "%GpsItemKindValue#" .. icons.Calendar .. "%*" .. " ",
      ["date-time-name"] = "%GpsItemKindValue#" .. icons.Table .. "%*" .. " ",
      ["inline-table-name"] = "%GpsItemKindProperty#" .. icons.Calendar .. "%*" .. " ",
      ["time-name"] = "%GpsItemKindValue#" .. icons.Watch .. "%*" .. " ",
      ["module-name"] = "%GpsItemKindModule#" .. icons.Module .. "%*" .. " ",
   },
}

gps.setup(options)

```

First set highlight colors to the symbols

**Comment by LamprosPitsillos** [comment]
> those Gpsitemkind.. stuff are the highlight groups, I assume that u know how to define highlight groups with the new nvim api

No i do not know,
I did copy from your config before posting here, but it didn't work, this is the part i was missing surely!!
I will search around your config and the docs (:h api , :h highlight-groups) and i should be able to figure it out.
Thank you!

**Comment by siduck** [comment]
@LamprosPitsillos 
```lua
local hl_groups = {
     Normal = {
          fg = "#ffffff",
          bg = "#000000",
     },

     Comment = {
          bold = true,
          italic = true,
     },

     Statusline = {
          bg = "abc", -- the hex color u want gps to take as bg
     },
}

for key, val in pairs(hl_groups) do
     vim.api.nvim_set_hl(0, key, val)
end
```

check the docs for deep understanding, i showed u a basic example c: 

my config btw https://github.com/NvChad/NvChad :joy:

**Comment by SmiteshP** [comment]
> > I defined a separate list of highlight groups for GPS ( which changes fg/bg color of the symbols) and change bg color of "Statusline" highlight group, ig gps uses that for its text
> 
> Could you please explain a bit more on how you fixed this? I am having a hard time adding colors to gps-nvim. Thanks

Hey @LamprosPitsillos ! Could you try out my new plugin nvim-navic? I have added colours functionality in it.
