### ISSUE TITLE
[Feature Request]: Allow having/changing highlights for the icons of groups

### ISSUE THREAD

**Issue by MordechaiHadad** [SmiteshP/nvim-gps#110]
I am talking something like:
```lua
	highlights = {
		disable_for_group_name = true,
		["class-name"] = { fg = "blue"},      -- Classes and class-like objects
		["function-name"] ={fg = "orange"},   -- Functions
		["method-name"] = {fg = "red"},     -- Methods (functions inside class-like objects)
	},
```

I know it is probably possible with `gps.get_data()` but it will probably be a hassle to achieve.

**Comment by SmiteshP** [comment]
Hey @MordechaiHadad ! Could you try out my new plugin nvim-navic. It improves on nvim-gps and used Lsp instead of treesitter. Also added colored icons support to it.

**Comment by MordechaiHadad** [comment]
@SmiteshP ayo this is awesome, what exactly made you move development to the new plugin?

**Comment by gegoune** [comment]
@SmiteshP how about merging two plugins together with both methods of retrieving position available? Could have a LSP enabled by default with fallback to treesitter if no LSP functionality is available. Or is it too much of a maintenance burden?

**Comment by MordechaiHadad** [comment]
@gegoune sounds like a pretty cool idea!

**Comment by MordechaiHadad** [comment]
@SmiteshP what do you think of this?

**Comment by SmiteshP** [comment]
>@SmiteshP how about merging two plugins together with both methods of retrieving position available? Could have a LSP enabled by default with fallback to treesitter if no LSP functionality is available. Or is it too much of a maintenance burden?

Hey @MordechaiHadad @gegoune
I answered this question in https://github.com/SmiteshP/nvim-navic/issues/6

**Comment by MordechaiHadad** [comment]
@SmiteshP thank you for your work!
