### ISSUE TITLE
unable to setup nvim-gps

### ISSUE THREAD

**Issue by zawedcvg** [SmiteshP/nvim-gps#14]
have tried installing it with vundle and this errors shows up on opening neovim after doing the required setup.

Error detected while processing /home/userName/.config/nvim/autoload/plugged/nvim-gps/plugin/nvim-gps.vim:
line    1:
E5108: Error executing lua [string ":lua"]:1: module 'nvim-gps.internal' not found:
        no field package.preload['nvim-gps.internal']
        no file './nvim-gps/internal.lua'
        no file '/usr/share/luajit-2.1.0-beta3/nvim-gps/internal.lua'
        no file '/usr/local/share/lua/5.1/nvim-gps/internal.lua'
        no file '/usr/local/share/lua/5.1/nvim-gps/internal/init.lua'
        no file '/usr/share/lua/5.1/nvim-gps/internal.lua'
        no file '/usr/share/lua/5.1/nvim-gps/internal/init.lua'
        no file './nvim-gps/internal.so'
        no file '/usr/local/lib/lua/5.1/nvim-gps/internal.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/nvim-gps/internal.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './nvim-gps.so'
        no file '/usr/local/lib/lua/5.1/nvim-gps.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/nvim-gps.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by SmiteshP** [comment]
Hmm... this is weird. Are you lazy loading the plugin?

**Comment by zawedcvg** [comment]
No I am not lazyloading the plugin, and yes that file does exist

**Comment by SmiteshP** [comment]
I am not sure whats causing this issue. I have structed my plugin like any other plugin 🤔 
Could you try adding this line somewhere in your init.vim
```
set rtp+=/home/userName/.config/nvim/autoload/plugged/nvim-gps
```

**Comment by zawedcvg** [comment]
yeah now that I have done this, it works fine. Thanks! Though it is a bit curious why vundle wasn't able to handle this. Probably mention this in the readme?

**Comment by SmiteshP** [comment]
I am glad it worked! Yep, it is weird. I will have to look into this, whether I am missing something.
