### ISSUE TITLE
Error with formatting

### ISSUE THREAD

**Issue by p00f** [SmiteshP/nvim-gps#15]
![image](https://user-images.githubusercontent.com/36493671/132117125-3f828e26-001d-4919-ab81-f5da0b7e5996.png)

I have a `BufWritePre` autocommand which does `vim.lsp.buf.formatting_sync()`. In this situation when the formatter shortens
```rust
async fn foo() {



}
```
to
```rust
async fn foo() {}
```
I get this error
`nvim-gps/lua/nvim-gps/init.lua:39: attempt to concatenate local 'capture_text' (a nil value)`

**Comment by p00f** [comment]
I can't reproduce this :/

**Comment by SmiteshP** [comment]
Hmm.. this shouldn't occur 🤔 . If some node is captured, it should return some text. 
Hopefully this was just a one time error 🤷🏽‍♂️
