### ISSUE TITLE
Add more path node types

### ISSUE THREAD

**Issue by Hubro** [SmiteshP/nvim-gps#17]
Currently, each node in the path can be either:

- Classes and class-like objects
- Functions
- Methods (functions inside class-like objects)

And each such "symbol type" can be configured with an icon.

Would you consider adding more symbol types for languages where the current types don't map cleanly?

In particular I'm missing two common symbol types:

- Container (For Ruby modules, JavaScript objects, YAML mappings etc.)
- Tag (For any markup languages like HTML/XML or languages with embedded XML like tags such as JSX, Svelte, Vue etc.)

Default "Container" icon could be `⛶` (SQUARE FOUR CORNERS) and default "Tag" icon could be `⛌` (CROSSING LANES).

**Comment by SmiteshP** [comment]
Yeah, that would be great. I was already considering adding something like a "container" for lua tables, but was't sure if it would be useful in any other languages.

**Comment by SmiteshP** [comment]
Although I don't have a lot of experience with html, from what I know html tags can be quite deeply nested. In you opinion, do you think it is necessary to know context of each tag? 🤔

**Comment by Hubro** [comment]
> I don't have a lot of experience with html, but from what I know html tags can be quite deeply nested. In you opinion, do you think it is necessary to know context of each tag?

A well formatted HTML document shouldn't be *too* deeply nested. I'm a big fan of how it works in VSCode:

![image](https://user-images.githubusercontent.com/597206/132672219-a634ffd2-a001-4a2c-9b0c-110f1212e6e8.png)

I don't suppose it would be possible to extract IDs and classes and append them to each segment in the path? :thinking: I guess that would require some custom code, right?

**Comment by SmiteshP** [comment]
> I don't suppose it would be possible to extract IDs and classes and append them to each segment in the path? thinking I guess that would require some custom code, right?

I think this can be done. I recently added the ability to setup special transform function for each language. So once we capture the text in the start tag, we can use some special regex on it to extract ID and class name date from it.

**Comment by SmiteshP** [comment]
Have a look at this line of a custom transform function for c++
https://github.com/SmiteshP/nvim-gps/blob/05f2afa363b3e9cf6cb8677276dd869b887b791c/lua/nvim-gps/init.lua#L45
Here I am using regex to extract more information from the text

**Comment by Hubro** [comment]
Nice! And they can also be overridden through config, very cool. Maybe I'll contribute queries and transforms for a couple of languages this weekend if I can find the time. (HTML and YANG)

**Comment by SmiteshP** [comment]
> Nice! And they can also be overridden through config, very cool.

The transform functions cannot be overridden by config right now 😓 

> Maybe I'll contribute queries and transforms for a couple of languages this weekend if I can find the time. (HTML and YANG)

That would be awesome!! 😄

**Comment by Hubro** [comment]
> > Nice! And they can also be overridden through config, very cool.
> 
> The transform functions cannot be overridden by config right now 

Oh, I just skimmed this block and misunderstood :smile: 

https://github.com/SmiteshP/nvim-gps/blob/05f2afa363b3e9cf6cb8677276dd869b887b791c/lua/nvim-gps/init.lua#L71-L77

But being able to override the transforms would be a nice advanced option, it would make it a lot easier to experiment with support for new languages and contribute them later.

**Comment by SmiteshP** [comment]
> But being able to override the transforms would be a nice advanced option, it would make it a lot easier to experiment with support for new languages and contribute them later.

I decided not to expose this option to end users because they don't have control over the treesitter queries. For contributors it would be more straight forward just to modify the code directly anyways.
Most plugin managers will setup a sim-link for you, if you mention the location of your repo. Just fork and clone this repo on your machine and add the location of the repo in the plugin manager.

For example for packer.nvim

https://github.com/SmiteshP/Dotfiles/blob/3fe3778c55515f822a98c326bb07c9768ecbec56/.config/nvim/lua/config/packer.lua#L34-L37

**Comment by rodhash** [comment]
These HTML tags would be really cool! I don't use Vscode but that's a nice thing in there.

I didn't get if this is something coming in the future, is it? Sorry I have little to none lua skills otherwise I'd offer help, perhaps it's time to start learning lua.

**Comment by SmiteshP** [comment]
> I didn't get if this is something coming in the future, is it?

Yep, I do want to add support for HTML. I haven't been getting much free time lately though. I will try my best to do this as soon as possible. PR's are always welcome :)

**Comment by SmiteshP** [comment]
Hey @Hubro and @rodhash !!
Could to try out the html branch and see if its working properly? I have tried to display the output like vscode, but before I merge I want to make sure I am not missing something 😄

**Comment by rodhash** [comment]
Hey @SmiteshP 

Sure testing new branch right now ... and it looks cool! Amazing!

In a quick test I noticed two things, not sure whether this is expected so let me show you.

1- When on **line 52** on img tag, it shows loads of classes and changes my statusline color to yellow-ish
2- When on **line 77** it has bunch of classes and show them all in that statusline but didn't change its color.


https://user-images.githubusercontent.com/29671981/134448657-24cd27e0-1e62-471a-8b72-2313dee5a368.mp4

**Comment by SmiteshP** [comment]
> 1- When on **line 52** on img tag, it shows loads of classes and changes my statusline color to yellow-ish
> 2- When on **line 77** it has bunch of classes and show them all in that statusline but didn't change its color.

nvim-gps is only providing the string output and doesn't do anything with colors. Its the statusline plugin coloring the component. 🤔

**Comment by rodhash** [comment]
Oh... yeah that makes sense, I use lualine so something in there must be set to change its color when certain condition matches, but weird thing is, now it suddenly stopped changing color :man_shrugging:

**Comment by rodhash** [comment]
Not sure if this is something worth it, but I was wondering if we can get it trimmed when the list of classes gets too long .. I suppose it must be done from lualine too right? Will look into that

**Comment by SmiteshP** [comment]
> It's probably not worth displaying _all_ class names. I think probably displaying just the first class name would be sufficient for most cases, and it would prevent the status line from exploding when using class-name based CSS libraries... If an element has both an ID and class names, perhaps only the ID should be displayed?

I am open to changing this behavior, right now I have just replicated the behavior of vscode's breadcrumbs.

**Comment by SmiteshP** [comment]
Closing this issue as I believe all the points raised here have been addressed.
