### ISSUE TITLE
File needs reload to show func name?

### ISSUE THREAD

**Issue by rodhash** [SmiteshP/nvim-gps#22]
Hi

I noticed that when we uncomment some code nvim-gps won't show its func name until file is reloaded, here a short vid:

I tested this in .py / .js / .cpp:

https://user-images.githubusercontent.com/29671981/133938074-4e6a4df6-41d5-46f2-81a5-f28c7858370d.mp4

The same thing happens if I use directly treesitter func so I suspect there won't be much gps can do, or is it possible to do something? I mean, showing the function name after the code is uncommented?

BTW, something else I'd like to ask pls:

Sometimes I find cool when treesitter function shows other stuff like loops, is it possible to enable it here? Not sure if we have some option for that.

Thank you

**Comment by SmiteshP** [comment]
I am not able to reproduce this effect, everything works fine for me. Which plugin are you using for commenting? I am using "terrortylor/nvim-comment" as my commenter plugin.

**Comment by SmiteshP** [comment]
> Sometimes I find cool when treesitter function shows other stuff like loops, is it possible to enable it here? Not sure if we have some option for that.

Currently there is no option for that. I intend this plugin to show what "named" scope you are working inside. There is no name for loops and other statements to display.

**Comment by rodhash** [comment]
> I am not able to reproduce this effect, everything works fine for me. Which plugin are you using for commenting? I am using "terrortylor/nvim-comment" as my commenter plugin.
> Does this also occur when you uncomment the line without using the comments plugin

Hi ..

That's a good point, I tried to remove the comments manually (without plugin) and the same thing happened. So since it works fine for you something else might be causing this.

And about the plugin I'm using Nerdcommenter, I have this thing installed for so long that I completely forgot its name, had to check my config files :rofl:

**Comment by SmiteshP** [comment]
> That's a good point, I tried to remove the comments manually (without plugin) and the same thing happened. So since it works fine for you something else might be causing this.

So this means we can rule out the comments plugin then 🤔 
Are you using neovim 0.5 stable? or are you on nightly 0.6? This may be a issue with treesitter itself? I am just speculating though, I can't help out much because I can't reproduce it :(

**Comment by rodhash** [comment]
Yeah for some reason it's happening with treesitter too, so weird.

I'm using stable version:
```
>_ nvim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by SmiteshP** [comment]
> Yeah for some reason it's happening with treesitter too, so weird.

Can you elaborate? does treesitter stop highlighting after uncommenting code? If so, then it will most certainly be a bug with treesitter, and then you could try opening a issue on neovim's github.

**Comment by rodhash** [comment]
Yes, I meant, this bug is happening with treesitter too, it looks like it can't highlight the block of code I just uncommented. I'm new to treesitter so I'm trying to find out if something in my setup is not properly set.

**Comment by SmiteshP** [comment]
> Yes, I meant, this bug is happening with treesitter too, it looks like it can't highlight the block of code I just uncommented. I'm new to treesitter so I'm trying to find out if something in my setup is not properly set.

Oh I see, In that case there is nothing I can do to help :(
Its best to file bug report on neovim's repo, maybe someone can help you out 😄
