### ISSUE TITLE
[ Feature Request ] Constant length for breadcrumbs

### ISSUE THREAD

**Issue by ModdedGamers** [SmiteshP/nvim-gps#25]
When I use this in my statusline, I like this being in the middle. However, as it resizes, my statusbar jumps around a lot. Could you make it so that when this plugin encounters a context that would make the statusbar line longer than it is, either truncate it or set that new length as the minimum length? So that the component would only get larger as you edit, not shorter. My other idea is instead of making it longer, set a fixed length, and anything past that length gets truncated in the middle, or at the beginning(as things like HTML have a lot of boilerplate at the beginning such as the `<html>` and `<body>` tags. Just a thought! I would contribute, but I don't know lua. :(

**Comment by SmiteshP** [comment]
I would consider this to be out of scope of this plugin. 
I feel there is no correct way of implementing this feature as everyone will have different ideas about how this component should integrate in their statusline. So I want to leave this to the end users to implement it. nvim-gps will just provide the string output and then its up to you to do whatever you want. 😄 
If you want it to have max length, just check for the length of the output and truncate accordingly. If you want it to have fixed length, then just add padding or truncate the output as you see fit.
