### ISSUE TITLE
nvim-gps requires all parsers to be installed

### ISSUE THREAD

**Issue by shadmansaleh** [SmiteshP/nvim-gps#3]
Currently if a parser of a supported language isn't installed `nvim-gps` fails to initialize.

It should just disable itself on filetype where parser isn't available.

Also this doesn't seem to recognize lua functions in following format
```lua
function_name  = function()
    .....
end
```

**Comment by katawful** [comment]
Also experiencing this problem. I only want the parsers I need installed so the current state is not usable for me

**Comment by zeitchef** [comment]
Same

**Comment by SmiteshP** [comment]
The issue with needing parser for all filetype should be resolved now.

**Comment by SmiteshP** [comment]
With the latest commit, I have added 2 more rules in lua to capture functions assigned to variables too.

**Comment by shadmansaleh** [comment]
Confirmed issue with parser not being installed and function assigned to variable is fixed .

Though named functions inside tables aren't recognized

like:
```lua
tbl = {
    fun_name = function()
       ...
    end
}

**Comment by SmiteshP** [comment]
@shadmansaleh I just added two more rules to capture these type of functions

**Comment by shadmansaleh** [comment]
Works now 👍🏽
