### ISSUE TITLE
A configurable 'depth' option

### ISSUE THREAD

**Issue by Bruflot** [SmiteshP/nvim-gps#37]
Let's say you have a function:
```cpp
NamespaceOne::NamespaceTwo::NamespaceThree::SomeClass::SomeFunction()
```
It's not always entirely useful to see the entire scope of the function. Instead, I think it would be neat if you could configure the (inverse) depth of scopes that nvim-gps will display. For example, with a depth of 2, it would show:
```cpp
SomeClass > SomeFunction
```
and with a depth of 3, it would show:
```cpp
NamespaceThree > SomeClass > SomeFunction
```

**Comment by SmiteshP** [comment]
Sure, this seems useful. I will try to implement this. :)

**Comment by SmiteshP** [comment]
Hello @Bruflot. You can checkout the latest commit for this feature.

**Comment by Bruflot** [comment]
Great job, thanks!
