### ISSUE TITLE
JSON does not honor `separator` config option

### ISSUE THREAD

**Issue by thetic** [SmiteshP/nvim-gps#42]
## Given

```lua
require('nvim-gps').setup({separator = '  '})
```

## Expected behavior

In a JSON file, `gps.get_location` uses `  ` as the separator.

## Actual behavior

In a JSON file, `gps.get_location` uses ` > ` as the separator.

**Comment by SmiteshP** [comment]
Hi @thetic !
Thanks for the bug report. The latest commit should have fixed this issue :)
