### ISSUE TITLE
Arrow Functions Not Showing in Statusline

### ISSUE THREAD

**Issue by LSleutsky** [SmiteshP/nvim-gps#48]
I have been using this plugin and it's really awesome, but I just realized of an issue where this does not work as intended.

I use SpaceVim as an editor primarily for ReactJS code, and let's say I have a function/method written like this:

```js
someRandomMethod() {
  ...
}
```

Whenever my cursor is inside the function, the statusline will in fact display `someRandomMethod()`. Great! However, if my cursor is inside an arrow method like so:

```js
myArrowMethod = () => {
  ...
}
```

then the statusline will display whatever the last _regular_ function (_see `someRandomMethod` above_) is, rather than `myArrowMethod`. For example, take the following code:

```js
componentDidMount() {
  ...
}

myFirstArrowMethod = () => {
  ...
}

mySecondArrowMethod = () => {
  ...
}
```

If my cursor was located inside of `mySecondArrowMethod`, then the statusline would still display `componentDidMount()`, because that is the first non-arrow syntax is finds. Is this something that has to do with a custom config of `nvim-gps` that I am missing? Was this a miss in the logic...?

If anyone has any guidance, it would be much appreciated. Thank you!

**Comment by SmiteshP** [comment]
> If my cursor was located inside of mySecondArrowMethod, then the statusline would still display componentDidMount(), because that is the first non-arrow syntax is finds. Is this something that has to do with a custom config of nvim-gps that I am missing? Was this a miss in the logic...?

Might be a bug. 🤔 

I am not familiar with java-script and React, but after trying out the given example nvimgps doesn't capture anything in it. After looking up the syntax, it seems the example is missing the `function` and `let` keywords for the regular function and arrow function respectively.

Also I would like to tag @Lazytangent in this issue. He has contributed to JS ans TS before and may be able to help.

**Comment by Lazytangent** [comment]
With my current setup using a nightly build of Neovim, I can't reproduce the bug. But it does come up when running Neovim v5 with SpaceVim. I can trigger the status line to update to show the right method if I save the file while in one of the arrow functions, which makes me think that the status line just doesn't update that section when the cursor moves around. I'll comment again when I get more time to test this out.

**Comment by LSleutsky** [comment]
> With my current setup using a nightly build of Neovim, I can't reproduce the bug. But it does come up when running Neovim v5 with SpaceVim. I can trigger the status line to update to show the right method if I save the file while in one of the arrow functions, which makes me think that the status line just doesn't update that section when the cursor moves around. I'll comment again when I get more time to test this out.

Hmm interesting. I guess SpaceVim is more specific in certain areas than I thought. In the previous post the author did write tho that in my examples there wasn’t a `let` or `function` keyword, which made me wonder. Is that what the plugin looks for. An explicitly defined `function`? If so, then how come bound React functions work normally? I’m looking into this as well, but am extremely new to Vim and Vimscript and Lua and whatnot. Will keep looking….

**Comment by Lazytangent** [comment]
The plugin uses Treesitter queries to parse the name of the function based on its location in the tree and the type of the node. I'm guessing @SmiteshP was running the code snippet from the original post outside of a `class` block, which is why he had to add the `let` and `function` keywords.

**Comment by Lazytangent** [comment]
Weird, I'm getting different results testing with a nightly build of Neovim and SpaceVim. It's updating just fine with this setup. I'm gonna do some more testing with the stable v0.5 build of Neovim and let you know what I see.

**Comment by Lazytangent** [comment]
So I have it working now with the stable build of Neovim and SpaceVim, turns out it was how I scoped the Vimscript function when using the plugin for the statusline.

I had
```vimscript
func! s:NvimGps() abort
...
endf

call SpaceVim#layers#core#statusline#register_sections('gps', function('s:NvimGps'))
```

Getting rid of the `s:` part in both the function name and the SpaceVim method got it to update properly. I have a feeling this wasn't your problem, but I figured I'd share anyways.

All that to say, I can't seem to reproduce your issue, @LSleutsky. Could you share how you've set up NvimGps in your statusline?

**Comment by LSleutsky** [comment]
> So I have it working now with the stable build of Neovim and SpaceVim, turns out it was how I scoped the Vimscript function when using the plugin for the statusline.
> 
> I had
> 
> ```
> func! s:NvimGps() abort
> ...
> endf
> 
> call SpaceVim#layers#core#statusline#register_sections('gps', function('s:NvimGps'))
> ```
> 
> Getting rid of the `s:` part in both the function name and the SpaceVim method got it to update properly. I have a feeling this wasn't your problem, but I figured I'd share anyways.
> 
> All that to say, I can't seem to reproduce your issue, @LSleutsky. Could you share how you've set up NvimGps in your statusline?

Hey my bad, I was unavailable for the last few days. So I was able to actually get it to display properly when removing the `s:` scoping in the function name and default SpaceVim call.

Thanks for troubleshooting with me, much appreciated!

Will be closing this...
