### ISSUE TITLE
[feature] integrate with lspkind

### ISSUE THREAD

**Issue by rebelot** [SmiteshP/nvim-gps#49]
would it be possible to integrate with lspkind-nvim or automatically infer the icons defined in `vim.lsp.protocol.CompletionItemKind`? I know users can do that manually, but I think this could provide a nice OOTB feeling of integration

EDIT: sharing my config
```lua
use({
    "SmiteshP/nvim-gps",
    after = { "nvim-treesitter", "lspkind-nvim" },
    module = "nvim-gps",
    config = function()
        local getkind = function(kind)
	    local kinds = vim.lsp.protocol.CompletionItemKind
            return kinds[kinds[kind]]:match("^.*%s")
        end
        require("nvim-gps").setup({
            icons = {
                ["class-name"] = getkind("Class"),
                ["function-name"] = getkind("Function"),
                ["method-name"] = getkind("Method"),
                ["container-name"] = getkind("Enum"),
                -- ["tag-name"] = ' '
            },
        })
    end,
})
```

**Comment by SmiteshP** [comment]
This should be possible but I would prefer not to depend on another plugin for symbols. It would limit me to use only those symbols. I would rather have the users make this decision for themselves. 🤷🏽‍♂️ 
Maybe adding a section to the readme file would be a better option for people looking for such integration 🤔
