### ISSUE TITLE
No leading separator printed

### ISSUE THREAD

**Issue by gegoune** [SmiteshP/nvim-gps#50]
Hey, I can see on your screencasts that there is leading separator printed before first node. I am not seeing it locally. Has that changed since screencasts were recorded? Is there a way to restore that functionality?

**Comment by SmiteshP** [comment]
It isn't a feature of nvim-gps, I was just my feline config adding the leading separator. 😅

This is the code I used to achieve it. 
```lua
table.insert(components.active[1], {
	provider = function()
		local text = gps.get_location()
		if #text ~= 0 then
			return '> '..text
		else
			return ''
		end
	end,
	enabled = function() return gps.is_available() end,
	right_sep = function() return { str = ' ', hl = mode_color().c } end,
	hl = function() return mode_color().c end
})
```

**Comment by gegoune** [comment]
Aha, I tried something very similar for lualine but it was always displaying prefix, I see what you did there to avoid that. Thanks!
