### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by zbirenbaum** [SmiteshP/nvim-gps#51]
So I lazy loaded the plugin after my statusline (which is also lazy loaded and shouldn't slow startup), and call the gps init within my statusline, but whenever this plugin is enabled a startup time log shows ~.020 longer, which is 20% of my prior startup time of .1 . Is there anyway to reduce this? It may seem short but the lag is visible and I can't warrant using the plugin for 20% slower startup speeds.

**Comment by SmiteshP** [comment]
I am not sure if lazy loading would slow down the setup function or not but I don't think there is anything that can be done to have a faster setup.
You could try using impatient.nvim to speed up your startup. It made my startup time a lot smaller. With impatient enabled, nvim-gps takes about 0.1 to 0.2 miliseconds to setup for me.
