### ISSUE TITLE
local 'config' (a nil value)

### ISSUE THREAD

**Issue by ruanyouxing** [SmiteshP/nvim-gps#55]
i called function require('nvim-gps').get_location and recieve this error:
![image](https://user-images.githubusercontent.com/87190231/147375441-4a4d36bf-e80c-4c49-a322-47b71b3af2b7.png)
Can you fix this?

**Comment by SmiteshP** [comment]
Can you share how you setup nvim-gps and which filetype caused this error?

**Comment by ruanyouxing** [comment]
it shows no error, but now lualine config just get error "Unrecognized component"

**Comment by ruanyouxing** [comment]
![image](https://user-images.githubusercontent.com/87190231/147379244-8ce372ed-e50a-468b-bbe8-555da8a11c55.png)
![image](https://user-images.githubusercontent.com/87190231/147379254-ebd6d40b-443c-4375-9c49-545168526917.png)

**Comment by SmiteshP** [comment]
You are calling the functions, you just need to pass the functions to lualine. That is, remove the round brackets after gps.get_location and gps.is_available

Have a look at the example in README.

```lua
-- Lua
local gps = require("nvim-gps")

require("lualine").setup({
	sections = {
			lualine_c = {
				{ gps.get_location, cond = gps.is_available },
			}
	}
})
```

**Comment by ruanyouxing** [comment]
thanks
