### ISSUE TITLE
Default container icon not in nerdfonts

### ISSUE THREAD

**Issue by jdrouhard** [SmiteshP/nvim-gps#57]
It doesn't look like the default "container" icon is actually a nerd font icon. It looks like the icon is 0x26f6 which isn't in https://www.nerdfonts.com/cheat-sheet and my nerd font doesn't have a glyph for it.

**Comment by SmiteshP** [comment]
Hmm... Can you suggest a better alternative for the container icon, I don't like the default one either XD

**Comment by jdrouhard** [comment]
Not sure, but whatever icon you're using now isn't actually in the nerdfont glyph table, so I'm not sure what it's supposed to be 😄

**Comment by SmiteshP** [comment]
I actually like the icon suggested in issue #52, but I am afraid it may reverse text for some people

**Comment by jdrouhard** [comment]
Just add the direction isolates around the icon and it'll work for everyone (U+2066 before, U+2069 after). I think 0xfb85 would be a fine choice. I'm curious what your font renders the current container icon as?

**Comment by SmiteshP** [comment]
@jdrouhard It looks something like this for me. I am using Input Mono font patched with nerd fonts
![Screenshot from 2022-01-06 15-49-23](https://user-images.githubusercontent.com/43147494/148368038-3bab4af0-8973-4068-b460-7692f7673591.png)
