### ISSUE TITLE
same location for all buffers

### ISSUE THREAD

**Issue by smartding** [SmiteshP/nvim-gps#63]
I have 2 different buffers in 2 split windows.

I expect the status line to show different locations for the 2 buffers, but the status line shows the same location for the 2 buffers.

I'm using neovim 0.7, I use the express_line plugin: https://github.com/tjdevries/express_line.nvim

Below is a lua function I used to integrate nvim-gps with express_line:

```lua
local gps_context = function(_, _)
  local gps = require("nvim-gps")

  if gps.is_available() then
    return '[ ' .. gps.get_location() .. ' ]'
  else
    return ''
  end
end
```

To fix the issue, maybe the `is_available` and `get_location` function should both take buffer number as parameter?

**Comment by smartding** [comment]
Or I can show context only for focused buffer

**Comment by SmiteshP** [comment]
Hey! were you able to solve the issue yourself?

**Comment by smartding** [comment]
@SmiteshP 
The issue is still there, I just hide the location info for split windows that are not in focus.
