### ISSUE TITLE
Treesitter :TSModuleInfo crash

### ISSUE THREAD

**Issue by philipGaudreau** [SmiteshP/nvim-gps#64]
Hi, while trying to generate the report of `:TSModuleInfo nvim-gps`, i get the following error:

```
E5108: Error executing lua ...0SLv/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 32
stack traceback:
        [C]: in function '_ts_parse_query'
        ...0SLv/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:91: in function 'get_query'
        ...ite/pack/packer/start/nvim-gps/lua/nvim-gps/internal.lua:11: in function 'is_supported'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:349: in function 'is_enabled'
        ...acker/start/nvim-treesitter/lua/nvim-treesitter/info.lua:80: in function 'append_module_table'
        ...acker/start/nvim-treesitter/lua/nvim-treesitter/info.lua:113: in function 'print_info_modules'
        ...acker/start/nvim-treesitter/lua/nvim-treesitter/info.lua:142: in function 'run'
        [string ":lua"]:1: in main chunk
```

Exact nvim version is `NVIM v0.7.0-dev+997-g21cdecc8e` and I use the default config.

Hope you can reproduce!

If you need more information, let me know.

**Comment by philipGaudreau** [comment]
I usually use `ensure_installed = 'maintained'`. If I uninstall all languages and run `:TSModuleInfo nvim-gps` then it works, so it must be caused by a specific language.

**Comment by SmiteshP** [comment]
Yep, seems like the parser for elixir got updated.
Tagging @sbaildon as he might be able to help with this.

**Comment by SmiteshP** [comment]
I am not able to open treesitter playground on elixir files, not sure whats the issue there. But without playground its difficult to fix this 😞
