### ISSUE TITLE
function parameters

### ISSUE THREAD

**Issue by nyngwang** [SmiteshP/nvim-gps#67]
In the image the context is:

```
config > excluded_filetypes
```

while I expect it would show something like this: (anonymous function is represented via `func`)

```
func > use > config > setup > excluded_filetypes
```

<img src="https://user-images.githubusercontent.com/24765272/152643612-3c1063c8-ef0e-4c0a-b679-3daa37b8e9f8.png" width="500"><img src="https://user-images.githubusercontent.com/24765272/152643538-5fba3113-171a-469f-ad9e-2f96371df117.png" width="500">

**Comment by SmiteshP** [comment]
nvim-gps only shows named scopes.
here the `func` is anonymous, thus skipped. And `use` and `setup` are function calls so they aren't displayed.

**Comment by nyngwang** [comment]
@SmiteshP: Could you provide an option for customization? It's boring to just show the named scopes :(
