### ISSUE TITLE
Programmatic interface of get_location()

### ISSUE THREAD

**Issue by wookayin** [SmiteshP/nvim-gps#68]
Thanks for the great plugin, I love that it works very well and fast.

I often need to access the (nested) location programmatically. It would be great if there is a function similar to `get_location()` that returns the location/hierarchy as a Lua table (list). The downside of current `get_location()` is that this is just a human-readable string that is ready for directly plugging into statusline plugins. For instance, I would want to search the parent/ancestor scope.

For instance, for the following lua file:
```
function foo()
  local function bar()
    local function baz()
      |
    end
  end
end
```

`gps.get_location()` will return `" foo >  bar >  baz"`, but what I would want to get is something like

```lua
{
   {name = "foo",
    type = "function-name",  -- or id  =
   },  
   {name = "bar",
    type = "function-name",
   },
   {name = "baz",
    type = "function-name",
   },
}
```

It will be pretty straightforward to implement this so I could make a PR, but there are some things to decide -- such as the name of function, the data structure (or field key names). Any opinions?

**Comment by SmiteshP** [comment]
Yep! I have been wanting to do this for sometime. But to me it seems I will have to rewrite/reorganize most of the code so I have been procrastinating on this 😆.
 
> It will be pretty straightforward to implement this so I could make a PR, but there are some things to decide -- such as the name of function, the data structure (or field key names). Any opinions?

It would be great if you make PR 🚀 
The table format you suggest looks good, the name maybe could be `get_location_table` 🤔

**Comment by SmiteshP** [comment]
Hey @wookayin!
Have a look at the latest commit, I have added a get_data function that will return the table information
