### ISSUE TITLE
Dynamic update support

### ISSUE THREAD

**Issue by wookayin** [SmiteshP/nvim-gps#69]
It looks like that the context is not automatically updated while editing. Until I reload the file (so that GPS query can refresh), nvim-gps fails to show the context for newly added scopes.

![Screenshot](https://user-images.githubusercontent.com/1009873/152883105-87c4a28f-d015-4451-a01c-63a9890cd442.gif)

It would be great if we can support dynamic update of the context information powered by treesitter!

**Comment by SmiteshP** [comment]
It should update dynamically. As soon as you exit insert mode, nvim-gps asks treesitter for new information to show. It seems that for some reason your treesitter isn't providing latest information 🤔 

https://user-images.githubusercontent.com/43147494/152925448-9175dd66-e895-4ca2-a2a6-c02015036ae1.mp4

**Comment by wookayin** [comment]
Hmm interesting. I am new to treesitter, so have no concrete ideas yet on how to debug this. FYI, my treesitter parser and plugins are up-to-date (and neovim is nightly-master). I have nothing special in my config, and `:checkhealth nvim-treesitter` seems fine.

The `TSPlayground` window also doesn't update and gets out of sync, so this might be related to the treesitter or its config itself.

**Comment by wookayin** [comment]
@SmiteshP Is treesitter-playground as well automatically updating as you change the text?

**Comment by SmiteshP** [comment]
> @SmiteshP Is treesitter-playground as well automatically updating as you change the text?

Yep, playground should also update on the fly. So this means the issue is definitely with treesitter. You could try opening a issue on nvim-treesitter repo, they should be able to help.

**Comment by wookayin** [comment]
Surprisingly, [nvim-treesitter/nvim-treesitter#2492](https://github.com/nvim-treesitter/nvim-treesitter/issues/2492#issuecomment-1033049114) says that currently the module `highlight` is required to make on-the-fly update work properly.

**Comment by wookayin** [comment]
@SmiteshP So from the discussion nvim-treesitter/nvim-treesitter#2492 (-> nvim-treesitter/playground#64), it seems calling the parser to update the syntax tree for the current buffer (i.e., `parser:parse(buf, lang)`) is the responsibility of downstream treesitter plugins. Apparently both playground and nvim-gps missed that (and many other treesitter plugins probably also aren't aware of that).

I can confirm that adding the following lines somewhere in `M.get_location()` makes the syntax tree is updated, despite `highlight { enabled = false }`. 
```
	-- Request treesitter parser to update the syntax tree.
	local parser = ts_parsers.get_parser(vim.fn.bufnr(), filelang)
	parser:parse()
```
But this would be too excessive, frequent call because `get_location()` is usually called from statusline. A better way would be having some autocmd (like `InsertLeave` autocmd) set up, but I'm not sure this is something `nvim-gps` is responsible for or users are supposed to have it configuring treesitter. Either way, if I get convinced, I will make a PR for nvim-gps.

**Comment by wookayin** [comment]
@SmiteshP So the conclusion is that ensuring the parse tree is up-to-date is the module's responsibility, which is however often subsumed when the treesitter `highlight` module is enabled. I submitted a PR #70 that fixes this bug, even when the `highlight` module is absent.

**Comment by SmiteshP** [comment]
Oh interesting! I did use to have an `InsertLeave` autocommand to update the parser but at some point I realised everything works fine without it too, so I removed it. 😆
