### ISSUE TITLE
Module 'nvim-treesitter.query' not found

### ISSUE THREAD

**Issue by Ritzier** [SmiteshP/nvim-gps#82]
Error detected while processing /home/ritzier/.local/share/nvim/site/pack/packer/start/nvim-gps/plugin/nvim-gps.vim:   
line    1:                                                                                                             
E5108: Error executing lua ...ite/pack/packer/start/nvim-gps/lua/nvim-gps/internal.lua:1: module 'nvim-treesitter.query'

**Comment by SmiteshP** [comment]
Have you installed `nvim-treesitter` plugin too? nvim-gps depends on it.

**Comment by SmiteshP** [comment]
Closing, hopefully you were able to fix it.

**Comment by fgheng** [comment]
I have the same error and I have alse installed nvim-treesitter

**Comment by Ritzier** [comment]
Try remove these two plugins, install nvim-treesitter and then install nvim-gps

**Comment by rodamaral** [comment]
I had the same problem using Packer. I fixed the issue by adding a **_after_** clause:

```lua
-- Simple statusline component that shows what scope you are working inside
use {
    'SmiteshP/nvim-gps',
    after = 'nvim-treesitter',
    requires = { 'nvim-treesitter/nvim-treesitter' },
    config = function()
        require('nvim-gps').setup()
    end,
}
```
