### ISSUE TITLE
Slow performance on big C++ files

### ISSUE THREAD

**Issue by Shatur** [SmiteshP/nvim-gps#88]
I've noticed that in large C++ files (22k lines, generated file) the cursor moves with a very noticeable delay if you move it quickly.

I would suggest to add a configurable delay into condition to avoid location calculation on every cursor move.

**Comment by SmiteshP** [comment]
Hey @Shatur !
Yep, treesitter can be slow on large files.
One work around that you can implement for this is to create a buffer varable `vim.b.gps` and print that in the statusline. And setup a `CursorHold` autocmd that will update the variable `vim.b.gps = gps.get_location()`. Also you can throw in a `vim.cmd [[ redrawstatus ]]` for good measure.
This will cause the function to run only on Cursor hold and keep experience smooth even on large files. But of course you will lose the on the fly updates while scrolling.
