### ISSUE TITLE
[Bug] nvim treesitter get node text has been deprecated

### ISSUE THREAD

**Issue by akinsho** [SmiteshP/nvim-gps#89]
It seems that in a recent nvim-treesitter update the `ts_utils.get_node_text` helper function has been deprecated in favour of using the now builting `vim.treesitter.get_node_text` this causes users on 0.7.0 using this plugin to see errors on startup.

Reference: https://github.com/nvim-treesitter/nvim-treesitter/commit/c3848e713a8272e524a7eabe9eb0897cf2d6932e

**Comment by SmiteshP** [comment]
Hmm.. does this mean I will have to drop support for the older versions of neovim?
