### ISSUE TITLE
bug: crashes in go with multiple type declaration

### ISSUE THREAD

**Issue by srafi1** [SmiteshP/nvim-gps#9]
I get the following error when running `require'nvim-gps'.get_location()` on line 3 of the following code snippet. It works fine if I remove struct B from the declaration (while leaving the parentheses).

Error:
```
E5108: Error executing lua ...im/site/pack/packer/start/nvim-gps/lua/nvim-gps/init.lua:129: attempt to concatenate a nil value
```

Code snippet:
```go
package main

type (
	A struct {
		field1 int
	}
	B struct {
		field1 int
	}
)

```

**Comment by SmiteshP** [comment]
Hey @srafi1! Thanks for the bug report, the issue should be solved now with the latest commit
