### ISSUE TITLE
Add golang package

### ISSUE THREAD

**Issue by kassio** [SmiteshP/nvim-gps#95]
Would be nice if we could add the golang package as the first item of the nvim-gps list. 

Currently we have:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/120483/165592985-5a11c2e5-459b-4393-bd19-e1aa2142dde5.png">

I'd like to have something like (where the first `main` is the `package_identifier`):

<img width="104" alt="image" src="https://user-images.githubusercontent.com/120483/165593185-90aa17f2-982e-4d6e-a913-3ab00612f352.png">

**Comment by SmiteshP** [comment]
Hey! @kassio 

It would not be possible to add package name as treesitter returns its scope to be only the first line. That is, the other functions methods aren't child nodes of the package node.
Technicalities aside, IMO it would make much sense to have the package name constantly show up throughout the whole file. It would take up valuabe space on statusline 😆 

And about the method and type being inverted. It is a bug! Will fix it asap

**Comment by kassio** [comment]
> Technicalities aside, IMO it wouldn't make much sense to have the package name constantly show up throughout the whole file. It would take up valuabe space on statusline 😆

I understand this point, and to be honest I was on the fence about that for a while. But I work in a large go project where all the packages have more than one file, and some functions/method names are duplicated among packages. Therefore, IMHO, having the current package name would be useful when jumping among files. Though, I understand the current limitations and will try to find another solution. 

Thanks for looking into this. 😄
