### ISSUE TITLE
[Bug] Missing text error on exiting neovim

### ISSUE THREAD

**Issue by akinsho** [SmiteshP/nvim-gps#98]
Some function seems to be running whilst neovim is trying to exit, leading to a missing value. It seems to be querying treesitter for the current text whilst leaving nvim.

```
Error executing vim.schedule lua callback: ...HEAD-8f95f3e/share/nvim/runtime/lua/vim/lsp/handlers.lua:16: Vim(redraw):E5108: Error executing lua ...im/site/pack/packer/start/nvim-gps/lua/nvim-gps/init.lua:330: bad argument #1 to 'gsub' (string expected, got nil)
stack traceback:
	[C]: in function 'gsub'
	...im/site/pack/packer/start/nvim-gps/lua/nvim-gps/init.lua:330: in function 'add_node_data'
	...im/site/pack/packer/start/nvim-gps/lua/nvim-gps/init.lua:358: in function 'get_data'
	...im/site/pack/packer/start/nvim-gps/lua/nvim-gps/init.lua:404: in function 'current_function'
	/Users/akin/.config/nvim/lua/as/statusline.lua:212: in function </Users/akin/.config/nvim/lua/as/statusline.lua:128>
	[C]: in function 'nvim_command'
	...HEAD-8f95f3e/share/nvim/runtime/lua/vim/lsp/handlers.lua:16: in function 'err_message'
	...HEAD-8f95f3e/share/nvim/runtime/lua/vim/lsp/handlers.lua:451: in function 'handler'
	...r/neovim/HEAD-8f95f3e/share/nvim/runtime/lua/vim/lsp.lua:796: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
	[C]: in function 'nvim_command'
	...HEAD-8f95f3e/share/nvim/runtime/lua/vim/lsp/handlers.lua:16: in function 'err_message'
	...HEAD-8f95f3e/share/nvim/runtime/lua/vim/lsp/handlers.lua:451: in function 'handler'
	...r/neovim/HEAD-8f95f3e/share/nvim/runtime/lua/vim/lsp.lua:796: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>%
```

**Comment by SmiteshP** [comment]
Can you share how to reproduce this issue?

**Comment by akinsho** [comment]
Apologies just posted quickly whilst trying to attend to something else and I had the stack track to hand.

I have `nvim-gps` configured to show in my statusline using
```lua
---The currently focused function
---@return string?
function M.current_function()
  local gps = require('nvim-gps')
  if gps.is_available() then
    return gps.get_location()
  end
end
```

and the plugin is configured using
```lua
use({
  'SmiteshP/nvim-gps',
  requires = 'nvim-treesitter/nvim-treesitter',
  config = function()
    require('nvim-gps').setup({})
  end,
})
```

It seems that there is an error in an LSP handler somewhere which calls `nvim_command('redraw')` which redraws my statusline. I think the LSP error is unrelated in the sense that whilst this is another issue I need to look into, although I don't see any visible signs of an error on leaving neovim from that I do see gps complain due to the redraw. I think the line where text is assumed to exist should have a guard checking if it does first.

**Comment by SmiteshP** [comment]
Hey @akinsho ! Sorry for the delayed response. Can you share exactly when this redraw gets triggered? I tried setting redraw to various BufLeave, WinLeave, etc, etc autocmds, but wasn't able to reproduce the error.

> I think the line where text is assumed to exist should have a guard checking if it does first.

Yeah, this can be done. But the text is retrieved using neovims treesitter api itself. So if neovim says that a node exists, it should be able to retrieve the text of that node, right? This seems like a bug in neovim's treesitter api. 🤔 What do you think?

**Comment by akinsho** [comment]
@SmiteshP I'd patched the issue in my local copy so haven't seen it for a little while I'll remove that for a bit and report back regarding what event is triggering the redraw not sure how easy it will be to track down though since this issue happens whilst exiting neovim so I'm not sure where a redraw might be being triggered from and catching it whilst leaving neovim I'm guessing will be quite hard, but I'll try and see
